### ISSUE TITLE
Not raise exception when fail upload metadata to meta-store

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/api-file-provider#14]
## Purpose
- bug report

## Description
- [meta-store へメタデータをアップロードする部分](https://github.com/dataware-tools/api-file-provider/blob/master/api/server.py#L396)で，リクエストが失敗しても例外が発生しない
- [ドキュメントには raise_for_status を呼び出せと書いてあった](https://docs.python-requests.org/en/master/user/quickstart/#response-status-codes)

**Comment by d-hayashi** [comment]
@yusukefs @WatanabeToshimitsu 
これって #17 で解決してます？

**Comment by WatanabeToshimitsu** [comment]
解決してました！

**Comment by WatanabeToshimitsu** [comment]
Resolved by https://github.com/dataware-tools/api-file-provider/pull/17
